### ISSUE TITLE
I get no IP-Adress for this domain: banking.vwfs.de

### ISSUE THREAD

**Issue by myssv** [TechnitiumSoftware/DnsServer#1074] opened 2024-10-14 21:16 UTC
Hi there,

using Technitium as a DNS server I got no IP address for the domain "banking.vwfs.de", "vwfs.de" is working fine.

![grafik](https://github.com/user-attachments/assets/362e39f0-d195-417d-896d-105a62948e19)

Switching to another DNS Server everything is fine:

![grafik](https://github.com/user-attachments/assets/433e65d6-ebcd-4403-be2b-84eb55bd94b9)

What can I do?

**Comment by myssv** [comment] 2024-10-14 21:28
Under cache I found this:

![grafik](https://github.com/user-attachments/assets/605d52a0-bf05-4c23-b431-566b2aa8328f)

**Comment by IngmarStein** [comment] 2024-10-14 21:42
Don't use `ping` to test DNS and instead use `dig` or `nslookup`.

I can reproduce the broken connectivity. The recursive resolver returns `NSDOMAIN`

```
❯ dig banking.vwfs.de

; <<>> DiG 9.20.2 <<>> banking.vwfs.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 39461
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;banking.vwfs.de.		IN	A

;; ANSWER SECTION:
banking.vwfs.de.	900	IN	CNAME	banking.glb.vwfs.de.

;; AUTHORITY SECTION:
vwfs.de.		900	IN	SOA	dnsglb1.vwfsag.de. dns-service.vwfs.com. 2017127652 10800 3600 2419200 900

;; Query time: 61 msec
;; SERVER: 192.168.1.8#53(192.168.1.8) (UDP)
;; WHEN: Mon Oct 14 23:36:06 CEST 2024
;; MSG SIZE  rcvd: 141
```

whereas 8.8.8.8 still has an `A` record:

```
❯ dig banking.vwfs.de @8.8.8.8

; <<>> DiG 9.20.2 <<>> banking.vwfs.de @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44150
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;banking.vwfs.de.		IN	A

;; ANSWER SECTION:
banking.vwfs.de.	649	IN	CNAME	banking.glb.vwfs.de.
banking.glb.vwfs.de.	30	IN	A	185.60.96.95

;; Query time: 35 msec
;; SERVER: 8.8.8.8#53(8.8.8.8) (UDP)
;; WHEN: Mon Oct 14 23:39:59 CEST 2024
;; MSG SIZE  rcvd: 86
```

**Comment by myssv** [comment] 2024-10-14 21:44
OK, so I only can wait or switch the DNS server whenever I will go banking there?

**Comment by ShreyasZare** [comment] 2024-10-15 07:24
Thanks for the feedback. The name servers for the domain name are returning NXDOMAIN response for the CNAME which you can [test here](https://dnsclient.net/#Recursive%20Query%20%7Brecursive-resolver%7D/banking.vwfs.de/A/UDP/false/). 

The SOA record in the authority section clearly indicates that the CNAME domain `banking.glb.vwfs.de`, which comes under it's authority `vwfs.de`, does not exists. So, this is a misconfiguration issue with the name servers.

Now, as per the standards, this is a valid NXDOMAIN response but you are seeing many resolvers able to resolver it. The reason probably is that they have detected this misconfiguration and are retrying to verify once again. Recursive resolvers have to implement a lot of weird testing logic to allow resolving domain names hosted on misconfigured name servers. This is one of the main reasons why its tough to implement recursive resolver since misconfigured name servers with various issues are littered all over the Internet.

Will see how I can add detection for this issue to allow resolving it. Will let you know when the fix is available. Till then as a workaround, you can create a Conditional Forwarder zone for `vwfs.de` and use any forwarder that is able to resolver it.

**Comment by Hemsby** [comment] 2024-10-15 07:31
Fully agree with @ShreyasZare here.  Create the CF zone and and have the working scenario.

**Comment by myssv** [comment] 2024-10-15 08:44
Thanks a lot for ypur input.
Can you please explain how to do it?

**Comment by ShreyasZare** [comment] 2024-10-15 09:11
> Thanks a lot for your input. Can you please explain how to do it?

Just switch to the Zones tab on the admin panel, click Add Zone, enter `vwfs.de` as the zone name, select Conditional Forwarder zone as the type, enter a forwarder address of your choice and the forwarder protocol, and add the zone. This will now cause the domain name to resolve via the conditional forwarder you set.

**Comment by myssv** [comment] 2024-10-15 09:14
Thanks a lot!

**Comment by ShreyasZare** [comment] 2024-10-19 14:59
Technitium DNS Server v13.1 is now available that fixes this issue. Do update and let me know your feedback.

**Closed by ShreyasZare** 2024-10-19 14:59 UTC
