### ISSUE TITLE
Problems with AdvancedForwarding.App

### ISSUE THREAD

**Issue by Potterli20** [TechnitiumSoftware/DnsServer#669] opened 2023-06-23 06:50 UTC
Is there a problem with this configuration file?
 {
    "enableForwarding": true,
    "forwarders": [
        {
            "name": "local-tcp",
            "dnssecValidation": true,
            "forwarderProtocol": "tcp",
            "forwarderAddresses": [
              "127.0.0.1:56",
              "127.0.0.1:57",
              "127.0.0.1:58",
              "127.0.0.1:59",
              "127.0.0.1:60"
            ]
          },
          {
            "name": "local-udp",
            "dnssecValidation": true,
            "forwarderProtocol": "udp",
            "forwarderAddresses": [
              "127.0.0.1:56",
              "127.0.0.1:57",
              "127.0.0.1:58",
              "127.0.0.1:59",
              "127.0.0.1:60"
            ]
          }
    ],
    "networkGroupMap": {
      "0.0.0.0/0": "everyone",
      "[::]/0": "everyone"
    },
    "groups": [
      {
        "name": "everyone",
        "enableForwarding": true,
        "forwardings": [
          {
            "forwarders": [
              "local-tcp",
              "local-udp"
            ],
            "domains": [
              "*"
            ]
          }
        ]
      }
    ]
  }

**Comment by ShreyasZare** [comment] 2023-06-23 07:27
Thanks for asking. The config looks good to me. Do you see any errors in the DNS logs?

**Comment by ShreyasZare** [comment] 2023-06-23 08:16
Thanks for the logs. I see the following error in it:

```
[2023-06-23 14:53:18 Local] DNS Server failed to resolve the request 'www.baidu.com. AAAA IN' using forwarders: 0.0.0.0:56, 0.0.0.0:57, 0.0.0.0:58, 0.0.0.0:59, 0.0.0.0:60, 0.0.0.0:56, 0.0.0.0:57, 0.0.0.0:58, 0.0.0.0:59, 0.0.0.0:60.
```

The above error means you had `0.0.0.0` address set as the forwarder addresses which is incorrect config.

```
[2023-06-23 14:50:55 Local] DNS Server failed to resolve the request 'apple.com. NS IN' using forwarders: 127.0.0.1:56, 127.0.0.1:57, 127.0.0.1:58, 127.0.0.1:59, 127.0.0.1:60, 127.0.0.1:56, 127.0.0.1:57, 127.0.0.1:58, 127.0.0.1:59, 127.0.0.1:60.
TechnitiumLibrary.Net.Dns.DnsClientNoResponseException: DnsClient failed to resolve the request 'apple.com. NS IN': request timed out.
```
In the above error, you have `127.0.0.1` addresses in the forwarder but they are not responding to requests in time. Try to increase the timeout value in Settings > Proxy & Forwarders section. Try checking if the forwarders that you have configured are indeed working well by querying them using the DNS Client tab on the DNS web panel.

**Comment by ShreyasZare** [comment] 2023-06-23 08:25
> > In the above error, you have `127.0.0.1` addresses in the forwarder but they are not responding to requests in time. Try to increase the timeout value in Settings > Proxy & Forwarders section. Try checking if the forwarders that you have configured are indeed working well by querying them using the DNS Client tab on the DNS web panel.
> 
> It's normal for me to forward the configuration It's just that it's not with such a configuration, but it's normal to use a file

Have you tested that those forwarders work using the DNS Client tool?

**Comment by ShreyasZare** [comment] 2023-06-23 08:28
> On the contrary, I have a problem now that I can't use TLS services, and I feel that there is no traffic access on the public network, and the intranet can be parsed

That's a separate problem which is unrelated to the forwarders not responding. You first need to check why the forwarders are not responding by querying them directly.

**Comment by ShreyasZare** [comment] 2023-06-24 05:57
> The log has been sent to your email The image is upstream of my server

Again it seems to be an issue with your forwarders. They are returning REFUSED response code which is why you see all the query logs with REFUSED RCODE.

Also, you do not need to use both the UDP and TCP forwarders together. Its of no use to use TCP forwarders too when you have UDP ones configured.

**Comment by ShreyasZare** [comment] 2023-06-24 06:10
> Is there any way to use TCP and UDP at the same time?

There is no point in even trying to attempt that. Just use UDP in you config. If the response is big then automatically the protocol will switch to TCP for it.

**Comment by ShreyasZare** [comment] 2023-06-24 07:22
> ![图片](https://user-images.githubusercontent.com/28734349/248447048-e2a16b21-fb1b-425a-acff-9c50ed330319.png) The first time there is no request, the second time there is a request, the cache is also set, there will be no request problem

In this case, if forwarder does not respond in time then the DNS server will return ServerFailure response after timeout.

**Comment by ShreyasZare** [comment] 2023-06-24 07:25
> This diary was just tested [2023-06-24(1).log](https://github.com/TechnitiumSoftware/DnsServer/files/11855572/2023-06-24.1.log)

```
TechnitiumLibrary.Net.Dns.DnsClientNoResponseException: DnsClient failed to recursively resolve the request 'connect.rom.miui.com. A IN': no response from name servers [ns4.dnsv5.com ([2402:4e00:1020:1250:0:983e:3bb8:54bb]), ns4.dnsv5.com (223.166.151.126), ns4.dnsv5.com (183.47.126.155), ns4.dnsv5.com (106.55.82.76), ns4.dnsv5.com (183.192.164.119), ns4.dnsv5.com (1.12.0.16), ns4.dnsv5.com (1.12.0.19), ns4.dnsv5.com (117.89.178.200), ns3.dnsv5.com ([2402:4e00:1430:11f9:0:983e:2e27:2604]), ns3.dnsv5.com (61.151.180.51), ns3.dnsv5.com (1.12.0.17), ns3.dnsv5.com (36.155.149.211), ns3.dnsv5.com (1.12.0.18), ns3.dnsv5.com (1.12.0.20), ns3.dnsv5.com (223.166.151.16), ns3.dnsv5.com (49.234.175.103)].
 ---> System.Net.Sockets.SocketException (101): Network is unreachable
```

There seems to be some kind of network issue causing this error.

**Comment by ShreyasZare** [comment] 2023-06-24 07:28
> This diary belongs to the dot server [2023-06-24(2).log](https://github.com/TechnitiumSoftware/DnsServer/files/11855595/2023-06-24.2.log)

```
TechnitiumLibrary.Net.Dns.DnsClientNoResponseException: DnsClient failed to recursively resolve the request 'staging.security.browser.miui.com. AAAA IN': no response from name servers [ns4.dnsv5.com ([2402:4e00:1020:1250:0:983e:3bb8:54bb]), ns3.dnsv5.com ([2402:4e00:1430:11f9:0:983e:2e27:2604]), ns3.dnsv5.com (223.166.151.16), ns4.dnsv5.com (1.12.0.16), ns4.dnsv5.com (1.12.0.19), ns4.dnsv5.com (183.47.126.155), ns4.dnsv5.com (117.89.178.200), ns3.dnsv5.com (1.12.0.17), ns4.dnsv5.com (106.55.82.76), ns3.dnsv5.com (1.12.0.20), ns3.dnsv5.com (36.155.149.211), ns3.dnsv5.com (49.234.175.103), ns3.dnsv5.com (61.151.180.51), ns4.dnsv5.com (223.166.151.126), ns4.dnsv5.com (183.192.164.119), ns3.dnsv5.com (1.12.0.18)].
 ---> System.Net.Sockets.SocketException (101): Network is unreachable
```

Same network issue here. You need to check if there are intermittent connectivity issues on the server. If its wired network then check the cables since loose cables can cause such issues.

**Comment by ShreyasZare** [comment] 2023-06-24 07:30
> > In this case, if forwarder does not respond in time then the DNS server will return ServerFailure response after timeout.
> 
> The transponder responds in time, but the DnsServer does not respond in time. I also set the cache, and it didn't work

If the forwarder responded in time then the DNS server will immediately respond to the original request. If you think this is not happening then run tcpdump on the server to capture packets and test it again.

**Comment by ShreyasZare** [comment] 2023-06-24 07:33
> ![1687591590110](https://user-images.githubusercontent.com/28734349/248451218-e519d5e2-354a-40e3-abb3-5236cde0a219.png)

The reason for this is "failure cache". If the DNS server does not get response from the forwarder in time then it will cache it as a "failure" for 60 seconds default. After that if you run the above test then the forwarder will seem like its responding but the DNS server will return ServerFailure from its cache.

If this is happening frequently then you need to increase the forwarder timeout values and also reduce the Failure TTL value in Settings > Cache section.

**Comment by ShreyasZare** [comment] 2023-06-24 07:41
> ![图片](https://user-images.githubusercontent.com/28734349/248451560-e890a7b7-2b8d-470a-802d-072e31c40f78.png)
> 
> I set it that way but it didn't work

You need to reset all the cache settings to default values and keep Cache Failure TTL to 10 sec. The current values you have is causing you issues.

- Enable Save Cache to disk option.
- Enable Serve Stale with the default TTL value (1200 is too small).
- Set Cache Maximum TTL to default value (1200 is too small).
- Set Prefetch Trigger to 9. Dont disable prefetch and auto prefetch.

All these are important and if there are not configured correctly then you will see frequently ServerFailure responses.

**Comment by ShreyasZare** [comment] 2023-06-24 08:07
> ![图片](https://user-images.githubusercontent.com/28734349/248453100-f82bca93-9fe9-4577-afac-39b403b94a32.png)

No, that is not correct json syntax. For adding two files, you will need to create two json objects as shown below:

```
"adguardUpstreams": [
  {
    "dnssecValidation": true,
    "configFile": "/root/dns-apple.txt"
  },
  {
    "dnssecValidation": true,
    "configFile": "/root/domain-full.txt"
  }
]
```

**Comment by ShreyasZare** [comment] 2023-06-24 10:04
> You can't completely take over the Forwarders function, or rely on the Forwarders function to set upstream

When you have forwarders configured, the DNS server will totally rely on it and will just act as a caching server.

**Comment by ShreyasZare** [comment] 2023-06-24 11:14
> > > You can't completely take over the Forwarders function, or rely on the Forwarders function to set upstream
> > 
> > 
> > When you have forwarders configured, the DNS server will totally rely on it and will just act as a caching server.
> 
> Is there any way to rely on the Forwarders feature to set upstream? I already have a DNS upstream server in my dns file, and I don't want to set up Forwarders else

It already relies on the forwarders that you have configured.

**Comment by ShreyasZare** [comment] 2023-06-24 11:53
> > > > > You can't completely take over the Forwarders function, or rely on the Forwarders function to set upstream
> > > > 
> > > > 
> > > > When you have forwarders configured, the DNS server will totally rely on it and will just act as a caching server.
> > > 
> > > 
> > > Is there any way to rely on the Forwarders feature to set upstream? I already have a DNS upstream server in my dns file, and I don't want to set up Forwarders else
> > 
> > 
> > It already relies on the forwarders that you have configured.
> 
> Actually, I don't want to rely on another repeater, it takes up too much memory. My DNS file is about 350m in size. That's why I didn't want to use another transponder

You can operate the DNS server only in two modes: recursive resolver, or forwarder. If you do not configure any forwarder then it will work as a recursive resolver.

Which DNS file are you talking about?

**Comment by ShreyasZare** [comment] 2023-06-24 12:03
> dns files: https://github.com/Potterli20/file/releases/download/dns-hosts/dns-adguardhome-blacklist_full_combine.txt
> 
> I want to use the dns file as the forwarder file so that I don't have to configure the upstream of Forwarders

That adguard file will be used as forwarders. Its one and the same thing. Either you configure forwarders in the app's config or you use the adguard file format. Internally, the DNS server is going to work the same way.

**Comment by ShreyasZare** [comment] 2023-06-24 12:11
> My DNS file is based on the adguard format, but I don't know why I need external forwarders to use DNS files, my DNS file already has a DNS upstream server

Yes, you do not need to define any extra forwarders anywhere else. The forwarders in the adguard file that you have will be used.

**Comment by ShreyasZare** [comment] 2023-06-24 12:24
> However, the problem is that I configured some domain names to resolve normally, and some domain names did not resolve but slowed down, as if they did not completely take over the Forwarders function, and needed Forwarders and configuration files to work together.

What do you mean when you say you want some domain names to resolve "normally"?

There is absolutely no difference between the forwarders you have in the adguard config or the forwarders you configure in the app's json config. Internally they are one and the same. The adguard config is just read by the app and it uses the forwarders in that file just like how the app uses the forwarders defined in the json config.

**Comment by ShreyasZare** [comment] 2023-06-24 12:52
> > > However, the problem is that I configured some domain names to resolve normally, and some domain names did not resolve but slowed down, as if they did not completely take over the Forwarders function, and needed Forwarders and configuration files to work together.
> > 
> > 
> > What do you mean when you say you want some domain names to resolve "normally"?
> > There is absolutely no difference between the forwarders you have in the adguard config or the forwarders you configure in the app's json config. Internally they are one and the same. The adguard config is just read by the app and it uses the forwarders in that file just like how the app uses the forwarders defined in the json config.
> 
> It's strange, I don't configure Forwarders upstream on my side, some domain names cannot be resolved, and all of the upstream of configured Forwarders can be resolved. I'll find a time to record a video for you. I don't know how to tell it to you either😭

Instead of video, just create a small sample adguard config with just 1 or 2 domain names in it and try to reproduce the problem Then share the config and how to test it so that I can also test it on my setup.

**Comment by ShreyasZare** [comment] 2023-06-24 14:40
> Oh, by the way, writing local upstream such as 127.0.0.1:54 in a dns file does not work. It is also the upstream of configuring Forwarders to take effect

Create a sample adguard config file with single upstream and test it once. If you are able to reproduce the issue then share the sample adguard config file so that I can try to reproduce the issue on my setup.

**Comment by ShreyasZare** [comment] 2023-06-25 10:47
> > > Oh, by the way, writing local upstream such as 127.0.0.1:54 in a dns file does not work. It is also the upstream of configuring Forwarders to take effect
> > 
> > 
> > Create a sample adguard config file with single upstream and test it once. If you are able to reproduce the issue then share the sample adguard config file so that I can try to reproduce the issue on my setup.
> 
> This is the configuration, pure IP file [#669 (comment)](https://github.com/TechnitiumSoftware/DnsServer/issues/669#issuecomment-1605471391)
> 
> { "enableForwarding": true, "networkGroupMap": { "0.0.0.0/0": "everyone,", "[::]/0": "everyone," }, "groups": [ { "name": "everyone", "enableForwarding": true, "adguardUpstreams": [ { "configFile": "/root/dns-local-127.0.0.1.txt" } ] } ] }

I tested the exact same config that you have on my local test setup and its working as expected without any issues.

**Comment by ShreyasZare** [comment] 2023-06-25 11:40
> > I tested the exact same config that you have on my local test setup and its working as expected without any issues.
> 
> It's so strange, I write local dns with a file, my configuration file does not take effect, even if the cache is cleaned, it does not work, and it takes effect only when I write forwarders
> 
> He has a request, but does not parse the IP when using dig

I would suggest that you run `tcpdump -i any -w dump.pcap` on the server with the same config and test it. After running the test query, stop `tcpdump` by pressing ctrl+c, and open the `dump.pcap` file in Wireshark to confirm if the DNS server is using your config. You can also share that file here or via email for analysis.

**Comment by ShreyasZare** [comment] 2023-08-05 14:56
> Detecting dns diversion files is slow on podman containers. My dns file size is about 550m. https://github.com/Potterli20/file/releases/download/dns-hosts-all/dnshosts-all-adguardhome-blacklist_full_combine.txt

The file size of 550MB is quite large so its going to take a while for the parsing. The issue mostly with the slowness is due to time it takes for the file to be read from disk, the actual parsing does not take much CPU. Also, check how much RAM there is available since the file is loaded into memory and thus if there is low memory then it will cause swapping which will use disk and slow everything down.

**Comment by ShreyasZare** [comment] 2023-08-05 14:59
> Also I would like to ask about support for parallel requests for doh, dot, doh3, doq?

If you have more than one forwarder configured then the requests are done in parallel. But the Forwarder Concurrency option in Settings > Proxy & Forwarders section is used so you may edit that option to allow more parallel requests as needed.

**Comment by ShreyasZare** [comment] 2023-08-06 10:25
> I'm also slow with 220m files, I'm now using the container podman. it's also slow to read, I see that the memory and cpu is not full, it's all around 5%, except just opening the container goes to around 100%, normal parsing wouldn't go to 10%. So a bit puzzled as to how to optimize the read data.

If you have SSD then keep the file on it and try. The issue mostly is slow IO from HDD but it could be something else too.

**Comment by ShreyasZare** [comment] 2023-08-06 10:26
> > > Also I would like to ask about support for parallel requests for doh, dot, doh3, doq?
> > 
> > 
> > If you have more than one forwarder configured then the requests are done in parallel. But the Forwarder Concurrency option in Settings > Proxy & Forwarders section is used so you may edit that option to allow more parallel requests as needed.
> 
> Is that a parallel request on advanced forwarding? I've set >dns upstream there to adjust it to 10 as well, but it doesn't feel like it's working.

The parallel query feature is tested and it does send parallel requests. You can test that by running packet capture with a test setup to confirm.

**Comment by ShreyasZare** [comment] 2023-08-06 11:57
> The # that follows in the dns triage file is not in effect. https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-for-domains

I tested the following sample config and it works as expected i.e. the `#` will cause `www.example.com` to get forwarded to `8.8.8.8` while `example.com` gets forwarded to `1.1.1.1`.
```
8.8.8.8
[/example.com/]1.1.1.1
[/www.example.com/]#
```

**Comment by ShreyasZare** [comment] 2023-08-08 10:21
> This is the diary, already running on the ssd [2023-08-07.log](https://github.com/TechnitiumSoftware/DnsServer/files/12282619/2023-08-07.log)

Thanks for the logs. 

```
System.FormatException: Invalid AdGuard Upstreams config file format: missing ']' bracket.
```
The error seen in the log suggest that there is a closing bracket missing in the adguard file. So, fixing this will make it work as expected.

The `https://doh.dns.apple.com/dns-query ([2403:300:a26:3000::192])` DoH server does not seem to answer any requests. For any requests it returns REFUSED response.

```
TechnitiumLibrary.Net.Dns.DnsClientException: No IP address was found for name server: dns64.dns.google
```
For using the `https://dns64.dns.google/dns-query` DoH server, you should either specify its IPv6 address in brackets OR you must enable Prefer IPv6 option in the Settings so that the DNS server will resolve the IPv6 address by default to make it work.

**Comment by ShreyasZare** [comment] 2023-08-08 10:51
> This file is working fine at adgh. 

Maybe their parser is ignoring this syntax error and thus its working. I would reocmmend that you check the file syntax once and add the missing ']' bracket.

> The apple doh can only use apple domains. 

In that case, using apple's DoH server as a forwarder will generate these errors. Its recommended not to use it to avoid performance issues.

> The podman container is also on ipv6 and the public network is also ipv6. 

I was mentioning the specific error for resolving `dns64.dns.google` domain for the DoH address. If you enable Prefer IPv6 option in the DNS server's Settings > General section then this error will go away and the DoH URL will work as expected.

> Does ipv6 work with the dns64 app?

The DNS64 app is useful only if you have a IPv6 only internet and your ISP has NAT64 service. Otherwise its of no use.

**Comment by ShreyasZare** [comment] 2023-08-09 10:06
> On my end, the test script is normal and formatted properly. I have a feeling it's not loading completely.

If possible please share one sample file which is failing to load so that I can test it locally. You can share here or over email.

**Comment by ShreyasZare** [comment] 2023-08-09 10:26
> > > On my end, the test script is normal and formatted properly. I have a feeling it's not loading completely.
> > 
> > 
> > If possible please share one sample file which is failing to load so that I can test it locally. You can share here or over email.
> 
> I'll e-mail it to you. It's a little big for me. 550m.

Do zip the file when sending it.

**Comment by ShreyasZare** [comment] 2023-08-10 13:20
> Then I don't quite understand, my cpu is j4125 system is debian dns is getting it in podman container, I load it in about 30 seconds, but when I write a script to update it, he doesn't load it. Even after clearing the dns program cache.

My test laptop is 7 year old with Intel i7 6700HQ and loading it in 21 seconds. If you update the file on disk, it will be automatically reloaded within 60 seconds. There is a timer which checks for file last modified date and if that has changed then reloads it. So, it may not load instantly and will need waiting a while for the timer to detect the file changes.

**Closed** 2023-10-31 16:11 UTC
