### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by amirmnoohi** [TechnitiumSoftware/DnsServer#395] opened 2022-05-06 08:21 UTC
Hi,

one of my DNS servers can not be started due to the below error:
```
System.Net.HttpListenerException (98): Address already in use
   at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure)
   at System.Net.HttpEndPointManager.AddPrefixInternal(String p, HttpListener listener)
   at System.Net.HttpEndPointManager.AddListener(HttpListener listener)
   at System.Net.HttpListener.Start()
   at DnsServerCore.DnsWebService.StartDnsWebService() in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 4425
   at DnsServerCore.DnsWebService.Start() in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 4579
   at DnsServerApp.Program.Main(String[] args) in Z:\Technitium\Projects\DnsServer\DnsServerApp\Program.cs:line 55

Technitium DNS Server is stopping...
Technitium DNS Server was stopped successfully.
```

However, there is not any open port except ssh(22):

![image](https://user-images.githubusercontent.com/19514168/167094741-062f01af-943b-483d-b2dd-d244f34deb95.png)

**Comment by ShreyasZare** [comment] 2022-05-06 08:45
Thanks for the feedback. Which OS are you running the DNS server on? Was the DNS server working earlier but stopped now? Have you tried rebooting the server?

**Comment by amirmnoohi** [comment] 2022-05-06 16:53
> Thanks for the feedback. Which OS are you running the DNS server on?

Ubuntu 22.04

> Was the DNS server working earlier but stopped now?

yes, suddenly it stopped working.

> Have you tried rebooting the server?

multiple times...

**Comment by ShreyasZare** [comment] 2022-05-07 07:12
Well, that is a strange issue which is not reproducible. Try once to reinstall the DNS server by running the install script again. It could also be an issue with the ubuntu server itself.

**Comment by amirmnoohi** [comment] 2022-05-07 11:22
After a day it suddenly goes up.
is there any way to backup automatically and then restore from disaster? (in general, where is the essential data, and after a fresh install, how can I restore backed-up data?)

**Comment by ShreyasZare** [comment] 2022-05-07 11:32
You can take backup for the entire DNS server using the "Backup Settings" option at the bottom right corner of Settings section. You will find the restore option in the same place.

**Comment by ShreyasZare** [comment] 2022-05-08 12:30
Closing this issue for now. Reopen if you have any more details.

**Closed by ShreyasZare** 2022-05-08 12:30 UTC

**Comment by amirmnoohi** [comment] 2022-06-01 16:39
Again it happened today.

Is there any way to send you the server credential to check it up?

Thanks

**Comment by ShreyasZare** [comment] 2022-06-03 13:52
> Again it happened today.
> 
> Is there any way to send you the server credential to check it up?
> 
> Thanks

That is not feasible due to time issues. Try changing the DNS web console from 5380 to something else and see if that helps.

**Comment by amirmnoohi** [comment] 2022-06-03 13:55
> > Again it happened today.
> > Is there any way to send you the server credential to check it up?
> > Thanks
> 
> That is not feasible due to time issues. Try changing the DNS web console from 5380 to something else and see if that helps.

how can I change port without accessing the web console?

**Comment by ShreyasZare** [comment] 2022-06-03 14:26
> 
> how can I change port without accessing the web console?

There is no option to change the port without using the web console / HTTP API. Since this issue is intermittent, you can change the port when you are able to access the web console.
