### ISSUE TITLE
DHCP Server failed to activate scope - Udp listener already exists for IP address

### ISSUE THREAD

**Issue by gtmadev** [TechnitiumSoftware/DnsServer#177] opened 2020-09-25 01:54 UTC
I created several scopes for a subnet. Each scope is designed to assign addresses with some different options for DNS, TTL, etc. However, I noticed that I can only enable one scope at a time? A scope is bound to an IP address???

This seems very odd. Why do I need a seperate interface (IP) for additional scopes? The scope will just have different options for different IP ranges. This is how I do it with ISC DHCP.

Here is the error message that is in the log.

`[2020-09-25 01:40:51 UTC] [192.168.43.253:56134] [admin] DHCP scope was enabled successfully: Open_1
[2020-09-25 01:40:53 UTC] [192.168.43.26:67] DHCP Server failed to activate scope: Knowns
DnsServerCore.Dhcp.DhcpServerException: Udp listener already exists for IP address: 192.168.43.26
   at DnsServerCore.Dhcp.DhcpServer.BindUdpListener(IPEndPoint dhcpEP) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dhcp\DhcpServer.cs:line 699
   at DnsServerCore.Dhcp.DhcpServer.ActivateScopeAsync(Scope scope, Boolean waitForInterface) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dhcp\DhcpServer.cs:line 774
[2020-09-25 01:40:53 UTC] [192.168.43.253:56134] DnsServerCore.WebServiceException: Failed to enable DHCP scope, please check logs for details: Knowns
   at DnsServerCore.WebService.EnableDhcpScopeAsync(HttpListenerRequest request) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebService.cs:line 3788
   at DnsServerCore.WebService.ProcessRequestAsync(HttpListenerRequest request, HttpListenerResponse response) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebService.cs:line 519`

**Comment by ShreyasZare** [comment] 2020-09-25 06:54
Thanks for the feedback. Will try to make changes to allow multiple scopes on a single network in next release.

**Comment by ShreyasZare** [comment] 2020-09-27 12:33
This issue has been fixed with v5.3 release. Try updating to the latest version and confirm if the issue is resolved.

**Closed by ShreyasZare** 2020-09-27 12:33 UTC
Labels: enhancement
