### ISSUE TITLE
Forwarder Zone AAAA NXDOMAIN

### ISSUE THREAD

**Issue by beatles1** [TechnitiumSoftware/DnsServer#1094] opened 2024-10-29 18:16 UTC
Hi,

Firstly, thank you so much for this software, it's awesome.

I've got some forwarder zones setup with some A and CNAME records to overwrite some stuff and using "This Server" for the forwarder.

The issue I'm having is that when doing an nslookup for one of these records held on the Technitium DNS server I get the A record but the AAAA comes back as NXDOMAIN rather than NOERROR because it's still forwarding that request.

I can't see a way to change this behaviour, I can't create an empty record for the AAAA and I can't see a setting to change this behaviour. The "Filter AAAA" app doesn't seem to have any affect here either.

Is there any workaround for this or could something be added in the future?

**Comment by ShreyasZare** [comment] 2024-10-30 07:28
Thanks for the post and compliments. The DNS server is returning NXDOMAIN response since its what it received from the upstream/forwarder. If you want to prevent from forwarding the requests for other record types then you can install the NO DATA app and add an APP record in the zone with the types defined. This will cause the DNS server to return NO DATA response i.e. empty response with NOERROR response code.

**Comment by beatles1** [comment] 2024-10-30 09:12
Ah yep, that sounds like what I was missing, thank you. I'll try later today and close this if it works.

**Comment by beatles1** [comment] 2024-10-30 10:35
I've managed to test now, added the NO DATA app and for my use case just added an app record for *.domain using this app and the config below and it's worked perfectly. Thank you!

`{
  "blockedTypes": [
    "AAAA"
  ]
}`

**Comment by ShreyasZare** [comment] 2024-10-30 10:37
You're welcome!

**Comment by beatles1** [comment] 2024-10-30 11:44
Okay, I am actually seeing something odd. Everything seems to work perfectly for the primary forwarder zone on my primary server. On my secondary server where it's a secondary forwarder zone any A requests which should be forwarded are come back as an empty result.

I can see the APP record has synced with the config showing only AAAA should be blocked but it's clearly also doing the same for A records. In the query logs I can see that on the primary server it's a recursive request on the primary whereas on the secondary the same query comes back as Authoritative NOERROR with no data.

Could this be a bug with this plugin in a secondary zone? I've tried restarting the secondary server and disabling and re-enabling the app on the primary but it's still the same. I'm using a catalog zone if that makes any difference.

**Comment by ShreyasZare** [comment] 2024-10-30 11:52
Thanks for the feedback. Please share screenshot of your secondary forwarder zone records and also the DNS Client output for the A record from secondary server.

**Comment by beatles1** [comment] 2024-10-30 12:01
Thanks for replying:
![image](https://github.com/user-attachments/assets/2d7685a2-0353-4347-850b-2cfa95f63907)
![image](https://github.com/user-attachments/assets/49e736e6-9559-4ddd-bb5e-05951e99cc6c)

**Comment by ShreyasZare** [comment] 2024-10-30 12:12
Please share how the A record is defined too.

**Comment by beatles1** [comment] 2024-10-30 12:17
So the record I'm querying has no record at all in this DNS server, it's just the upstream public server where there is a record. It's forwarding to itself and recursively looking it up on the primary but the secondary is authoritatively saying NODATA when I specifically request -q=a.

Sorry if I've misunderstood what you're asking for, I can find the A record in the upstream nameserver if required.

**Comment by ShreyasZare** [comment] 2024-10-30 12:22
Thanks for the details. I got the issue reproduced. There is a bug due to missing check for secondary forwarder zone. Will get this fixed in the upcoming update and let you know here.

Meanwhile, the fix would be to convert the secondary to forwarder zone till the next update is available.

**Comment by beatles1** [comment] 2024-10-30 13:41
Awesome, thank you!

**Comment by ShreyasZare** [comment] 2024-11-11 13:27
Technitium DNS Server v13.1.1 is now available which fixes this issue. Do update and let me know your feedback.

**Closed by ShreyasZare** 2024-11-11 13:27 UTC
