### ISSUE TITLE
DNS Server kind of breaking down regularly

### ISSUE THREAD

**Issue by tkpaul92** [TechnitiumSoftware/DnsServer#242] opened 2021-03-24 09:13 UTC
hello!

I have the server running as our internal company dns server, it forwards non-internal queries to isp dns, cloudflare, google external dns servers.
I have this problem for quite a while already, persisting over versions.
Sometimes (there is no visible timing pattern, seems random) the server stops working in a weird way.
While the problem persists, the server will respond to any queries only with empty reply or give ipv6 address only.
It seems that if the host does not have ipv6 it gives empty reply and if it does have, it only gives the ipv6 part as reply.
This is weird and causes everything to break because we dont have any ipv6 capability with our ISP and also not internally.
I have also verified that while this is going on, the internet connection itself is up and connections go in and out and also pings to ip addresses directly go through without issue.
Also in this timeframe the isp and cloudflare, google dns work without issue when queried directly by mobile phone at the same time.
It will only go back to normal after Windows Service restart so I have scheduled a nightly service restart, mostly that seemed to have helped prevent that this comes up most days, but sometimes the error comes up more often, also during the day, then I have to manually restart the service.
I have looked through DNS server settings and have not found anything obviously related, the checkbox to prefer ipv6 is not ticked.
I have looked through the log and have not found any obvious error lines that could be related.
This is what a log entry for a query looks like during the time the problem persists:
[2021-03-24 07:06:41 UTC] [192.168.0.4:64722] [UDP] QNAME: storage.googleapis.com; QTYPE: A; QCLASS: IN; RCODE: NameError; ANSWER: []
Is this a known problem, any suggestions what I could try?
Thanks in advance for any help and thanks for the software.

**Comment by ShreyasZare** [comment] 2021-03-24 10:13
Thanks for the feedback. Find response inline:
 
> I have the server running as our internal company dns server, it forwards non-internal queries to isp dns, cloudflare, google external dns servers.
> I have this problem for quite a while already, persisting over versions.

Are you running the latest version 6.0? Since there were bugs in previous versions that caused cache poisoning that were fixed in the latest update. But the bugs would create issues only if you were running the DNS server as a recursive resolver and from your description, you are using 3 forwarders so these bugs wont have affected your setup.

> Sometimes (there is no visible timing pattern, seems random) the server stops working in a weird way.
> While the problem persists, the server will respond to any queries only with empty reply or give ipv6 address only.
> It seems that if the host does not have ipv6 it gives empty reply and if it does have, it only gives the ipv6 part as reply.
> This is weird and causes everything to break because we dont have any ipv6 capability with our ISP and also not internally.

Tools like nslookup query for both A and AAAA records so when AAAA record is present for the domain name, you see it in the output. This has nothing to do with the IPv6 connectivity you have or the DNS server settings. The DNS server wont just return IPv6 record unless there was a specific query for AAAA record.

> I have also verified that while this is going on, the internet connection itself is up and connections go in and out and also pings to ip addresses directly go through without issue.
> Also in this timeframe the isp and cloudflare, google dns work without issue when queried directly by mobile phone at the same time.
> It will only go back to normal after Windows Service restart so I have scheduled a nightly service restart, mostly that seemed to have helped prevent that this comes up most days, but sometimes the error comes up more often, also during the day, then I have to manually restart the service.

I would recommend that when you see this issue, just use the web console and check Cache tab for the domain name giving issue. Do see what the cache has and also the parent zone for the domain name and see if anything looks strange. Do report anything you see when this issue is observed.

> I have looked through DNS server settings and have not found anything obviously related, the checkbox to prefer ipv6 is not ticked.

The prefer ipv6 setting is unlikely to cause any issue since it just to prefer ipv6 name server addresses when you have ipv6 connectivity. Also, this setting will be used when doing recursive resolution and wont do anything when you have forwarders setup.

> I have looked through the log and have not found any obvious error lines that could be related.
> This is what a log entry for a query looks like during the time the problem persists:
> [2021-03-24 07:06:41 UTC] [192.168.0.4:64722] [UDP] QNAME: storage.googleapis.com; QTYPE: A; QCLASS: IN; RCODE: NameError; ANSWER: []

The NameError response code is never generated by the DNS server for recursive resolution. There is no code which generates this response unless you have a zone hosted on the server and any sub domain does not exists. So, it is highly likely that one of your upstream server responded with NameError and that got cached.

> Is this a known problem, any suggestions what I could try?

For the DNS server using forwarders, there are no known issues reported till now. The only known issues which are fixed in latest update were in DNS caching when not using any forwarders i.e. when using recursive resolution.

Since that you are seeing NameError response and that you are using 3 forwarders, your ISP, Cloudflare, and Google, I would recommend that you drop you ISP from the forwarder and see if that makes any difference. ISP DNS servers may not always be well maintained which is why people in many networks resort to using 3rd party DNS providers.

> Thanks in advance for any help and thanks for the software.

You're most welcome. Thanks for the feedback.

**Comment by Potterli20** [comment] 2021-03-25 07:09
> Thanks for the feedback. Find response inline:
> 
> > I have the server running as our internal company dns server, it forwards non-internal queries to isp dns, cloudflare, google external dns servers.
> > I have this problem for quite a while already, persisting over versions.
> 
> Are you running the latest version 6.0? Since there were bugs in previous versions that caused cache poisoning that were fixed in the latest update. But the bugs would create issues only if you were running the DNS server as a recursive resolver and from your description, you are using 3 forwarders so these bugs wont have affected your setup.
> 
> > Sometimes (there is no visible timing pattern, seems random) the server stops working in a weird way.
> > While the problem persists, the server will respond to any queries only with empty reply or give ipv6 address only.
> > It seems that if the host does not have ipv6 it gives empty reply and if it does have, it only gives the ipv6 part as reply.
> > This is weird and causes everything to break because we dont have any ipv6 capability with our ISP and also not internally.
> 
> Tools like nslookup query for both A and AAAA records so when AAAA record is present for the domain name, you see it in the output. This has nothing to do with the IPv6 connectivity you have or the DNS server settings. The DNS server wont just return IPv6 record unless there was a specific query for AAAA record.
> 
> > I have also verified that while this is going on, the internet connection itself is up and connections go in and out and also pings to ip addresses directly go through without issue.
> > Also in this timeframe the isp and cloudflare, google dns work without issue when queried directly by mobile phone at the same time.
> > It will only go back to normal after Windows Service restart so I have scheduled a nightly service restart, mostly that seemed to have helped prevent that this comes up most days, but sometimes the error comes up more often, also during the day, then I have to manually restart the service.
> 
> I would recommend that when you see this issue, just use the web console and check Cache tab for the domain name giving issue. Do see what the cache has and also the parent zone for the domain name and see if anything looks strange. Do report anything you see when this issue is observed.
> 
> > I have looked through DNS server settings and have not found anything obviously related, the checkbox to prefer ipv6 is not ticked.
> 
> The prefer ipv6 setting is unlikely to cause any issue since it just to prefer ipv6 name server addresses when you have ipv6 connectivity. Also, this setting will be used when doing recursive resolution and wont do anything when you have forwarders setup.
> 
> > I have looked through the log and have not found any obvious error lines that could be related.
> > This is what a log entry for a query looks like during the time the problem persists:
> > [2021-03-24 07:06:41 UTC] [192.168.0.4:64722] [UDP] QNAME: storage.googleapis.com; QTYPE: A; QCLASS: IN; RCODE: NameError; ANSWER: []
> 
> The NameError response code is never generated by the DNS server for recursive resolution. There is no code which generates this response unless you have a zone hosted on the server and any sub domain does not exists. So, it is highly likely that one of your upstream server responded with NameError and that got cached.
> 
> > Is this a known problem, any suggestions what I could try?
> 
> For the DNS server using forwarders, there are no known issues reported till now. The only known issues which are fixed in latest update were in DNS caching when not using any forwarders i.e. when using recursive resolution.
> 
> Since that you are seeing NameError response and that you are using 3 forwarders, your ISP, Cloudflare, and Google, I would recommend that you drop you ISP from the forwarder and see if that makes any difference. ISP DNS servers may not always be well maintained which is why people in many networks resort to using 3rd party DNS providers.
> 
> > Thanks in advance for any help and thanks for the software.
> 
> You're most welcome. Thanks for the feedback.

Hahaha, I also have this problem. I just feel that I can't access DNS upstream, and it's the same with local DNS. # 238

**Comment by ShreyasZare** [comment] 2021-03-25 07:26
> 
> Hahaha, I also have this problem. I just feel that I can't access DNS upstream, and it's the same with local DNS. #238

Thanks for the response. The issue you described and the one here are very different. In fact, you provided pcap file where the DNS server was sending queries to the upstream and was getting response. There were no issues found in the pcap file and everything looked normal. Even the dashboard stats json in the pcap were normal. 

If you can provide specific details so that I can understand the issue then only it will be possible for me to get it fixed.

**Comment by tkpaul92** [comment] 2021-03-25 13:23
Hello and thanks for your swift response yesterday.
Ok, so I removed the ISP DNS server right away yesterday, but that did not seem to change anything.
Now today the issue came up again.
I copied out a few lines from the log at the bottom, not sure if they are related though.
I want to point out again whats going on when this is going on:
Browser gives error, visting the same site from all computers or pressing refresh 10 times does not change a thing, however and thats the weird part: When I do nslookup while this is going on, the second time it gives the right response and then that seems to be cached or something and then the site works in all browsers too. (but of course only that host itself, embedded pictures and such only work if I do the same for their image hostnames if they are on different host)

C:\Users\Paul>nslookup cnn.com
Server:  UnKnown
Address:  192.168.0.3

Name:    cnn.com
Addresses:  2a04:4e42:400::323
          2a04:4e42::323
          2a04:4e42:200::323
          2a04:4e42:600::323

C:\Users\Paul>nslookup cnn.com
Server:  UnKnown
Address:  192.168.0.3

Nicht autorisierende Antwort:
Name:    cnn.com
Addresses:  2a04:4e42::323
          2a04:4e42:600::323
          2a04:4e42:400::323
          2a04:4e42:200::323
          151.101.129.67
          151.101.193.67
          151.101.65.67
          151.101.1.67

C:\Users\Paul>nslookup www.cnn.com
Server:  UnKnown
Address:  192.168.0.3

Name:    turner-tls.map.fastly.net
Addresses:  2a04:4e42::323
          2a04:4e42:200::323
          2a04:4e42:600::323
          2a04:4e42:400::323
Aliases:  www.cnn.com

C:\Users\Paul>nslookup www.cnn.com
Server:  UnKnown
Address:  192.168.0.3

Nicht autorisierende Antwort:
Name:    turner-tls.map.fastly.net
Addresses:  2a04:4e42:400::323
          2a04:4e42:200::323
          2a04:4e42::323
          2a04:4e42:600::323
          151.101.1.67
          151.101.65.67
          151.101.129.67
          151.101.193.67
Aliases:  www.cnn.com

C:\Users\Paul>nslookup edition.cnn.com
Server:  UnKnown
Address:  192.168.0.3

Name:    edition.cnn.com
Addresses:  2a04:4e42:600::323
          2a04:4e42:400::323
          2a04:4e42::323
          2a04:4e42:200::323

C:\Users\Paul>nslookup edition.cnn.com
Server:  UnKnown
Address:  192.168.0.3

Nicht autorisierende Antwort:
Name:    edition.cnn.com
Addresses:  2a04:4e42:600::323
          2a04:4e42:400::323
          2a04:4e42::323
          2a04:4e42:200::323
          151.101.193.67
          151.101.129.67
          151.101.65.67
          151.101.1.67

[2021-03-25 13:47:00 Local] [0.0.0.0:0] [TCP] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at DnsServerCore.Dns.Zones.ZoneTree`1.FindNodeValue(Byte[] key, Node& closestNode, NodeValue& closestDelegation, NodeValue& closestAuthority) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\ZoneTree.cs:line 247
   at DnsServerCore.Dns.Zones.ZoneTree`1.FindZone(String domain, T& delegation, T& authority, Boolean& hasSubDomains) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\ZoneTree.cs:line 645
   at DnsServerCore.Dns.ZoneManagers.CacheZoneManager.Query(DnsDatagram request, Boolean serveStale) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\ZoneManagers\CacheZoneManager.cs:line 287
   at DnsServerCore.Dns.DnsServer.QueryCache(DnsDatagram request, Boolean serveStale) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 1764
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsDatagram request, IReadOnlyList`1 viaForwarders, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 1548
   at DnsServerCore.Dns.DnsServer.ProcessRecursiveQueryAsync(DnsDatagram request, IPEndPoint remoteEP, DnsTransportProtocol protocol, IReadOnlyList`1 viaForwarders, Boolean checkForCnameCloaking, Boolean cacheRefreshOperation) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 1456
   at DnsServerCore.Dns.DnsServer.ProcessQueryAsync(DnsDatagram request, IPEndPoint remoteEP, Boolean isRecursionAllowed, DnsTransportProtocol protocol) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 958
[2021-03-25 13:47:00 Local] [127.0.0.1:54814] [UDP] QNAME: go.technitium.com; QTYPE: A; QCLASS: IN; RCODE: NameError; ANSWER: []
[2021-03-25 13:47:00 Local] [127.0.0.1:56194] Check for update was done {updateAvailable: False;}
System.Net.Http.HttpRequestException: Der angegebene Host ist unbekannt. (go.technitium.com:443)
 ---> System.Net.Sockets.SocketException (11001): Der angegebene Host ist unbekannt.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DnsServerCore.DnsWebService.CheckForUpdateAsync(HttpListenerRequest request, JsonTextWriter jsonWriter) in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 1010
[2021-03-25 13:48:00 Local] [0.0.0.0:0] [TCP] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at DnsServerCore.Dns.Zones.ZoneTree`1.FindNodeValue(Byte[] key, Node& closestNode, NodeValue& closestDelegation, NodeValue& closestAuthority) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\ZoneTree.cs:line 247
   at DnsServerCore.Dns.Zones.ZoneTree`1.FindZone(String domain, T& delegation, T& authority, Boolean& hasSubDomains) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\Zones\ZoneTree.cs:line 645
   at DnsServerCore.Dns.ZoneManagers.CacheZoneManager.Query(DnsDatagram request, Boolean serveStale) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\ZoneManagers\CacheZoneManager.cs:line 287
   at DnsServerCore.Dns.DnsServer.QueryCache(DnsDatagram request, Boolean serveStale) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 1764
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsDatagram request, IReadOnlyList`1 viaForwarders, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 1548
   at DnsServerCore.Dns.DnsServer.ProcessRecursiveQueryAsync(DnsDatagram request, IPEndPoint remoteEP, DnsTransportProtocol protocol, IReadOnlyList`1 viaForwarders, Boolean checkForCnameCloaking, Boolean cacheRefreshOperation) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 1456
   at DnsServerCore.Dns.DnsServer.ProcessQueryAsync(DnsDatagram request, IPEndPoint remoteEP, Boolean isRecursionAllowed, DnsTransportProtocol protocol) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 958

**Comment by tkpaul92** [comment] 2021-03-25 13:35
Ok, sorry, i forget to write, yes I use the newest version.
And about the thing to check in cache tab, I will do that the next time this comes up.

**Comment by ShreyasZare** [comment] 2021-03-25 14:57
Thanks for the error logs. This could be the reason that the server is failing to return IPv4 addresses.

It looks like a very specific case when this is occurring since I haven't seen this error earlier. I have found one spot in code which possibly can cause it. Will try to reproduce the issue to confirm.

It would be quite helpful if you can send some screenshot of the cache for the domain that is failing to respond when this occurs again. The bug may even give you errors while trying to browse the cache. Do let me know anything that you see in there.

**Comment by ShreyasZare** [comment] 2021-03-25 14:58
Also, do try to use the built in DNS Client tab to query and post its response. That too would give some clues.

**Comment by ShreyasZare** [comment] 2021-03-27 09:09
@tkpaul92 : will you be willing to run beta version 6.1 on your setup? This will be helpful to see if the error that you reported was fixed since I am finding it difficult to reproduce this error.

As a precaution if you can export the backup zip file for the current installation and in a rare case if something does not work out with this beta version, you will be able to restore the zip file and have everything as-is like before.

**Comment by Potterli20** [comment] 2021-03-27 09:16
> @tkpaul92 : will you be willing to run beta version 6.1 on your setup? This will be helpful to see if the error that you reported was fixed since I am finding it difficult to reproduce this error.
> 
> As a precaution if you can export the backup zip file for the current installation and in a rare case if something does not work out with this beta version, you will be able to restore the zip file and have everything as-is like before.

You can provide the script of bate, I want to use it too, hahaha

**Comment by ShreyasZare** [comment] 2021-03-27 11:38
Here is the link to the v6.1 beta: https://download.technitium.com/dns/DnsServerSetup6.1beta.zip

Do let me know if you find any errors in the logs. Thanks.

**Comment by tkpaul92** [comment] 2021-03-27 22:11
> Here is the link to the v6.1 beta: https://download.technitium.com/dns/DnsServerSetup6.1beta.zip
> 
> Do let me know if you find any errors in the logs. Thanks.

thanks!
I have installed it and will report back.

**Comment by tkpaul92** [comment] 2021-03-27 22:25
![Picture_20210327_232105471](https://user-images.githubusercontent.com/81292047/112736483-68e7a080-8f53-11eb-8d08-a0c66b072911.jpg)
![Picture_20210327_232201208](https://user-images.githubusercontent.com/81292047/112736484-69803700-8f53-11eb-93c0-55e18908836f.jpg)

Thanks, however it looks like installation damaged something. The german error message pops up when trying to set the service to automatic start type and it means like "this service was marked for deletion.

**Comment by ShreyasZare** [comment] 2021-03-28 10:22
> Thanks, however it looks like installation damaged something. The german error message pops up when trying to set the service to automatic start type and it means like "this service was marked for deletion."

Rebooting will fix this issue. Its just that the old service was deleted but windows refuses to let it go completely and requires a reboot. After reboot if the service does not exists, just run the setup once more and it should be working.

**Comment by tkpaul92** [comment] 2021-03-28 15:38
> > Thanks, however it looks like installation damaged something. The german error message pops up when trying to set the service to automatic start type and it means like "this service was marked for deletion."
> 
> Rebooting will fix this issue. Its just that the old service was deleted but windows refuses to let it go completely and requires a reboot. After reboot if the service does not exists, just run the setup once more and it should be working.

ok, sorry, yes thanks, it is running now.

**Comment by ShreyasZare** [comment] 2021-03-29 08:09
> 
> ok, sorry, yes thanks, it is running now.

Good to know its installed. Dont configure the windows service for daily restarts for a couple of days and see if you get any errors in the logs. If this works out then I can release this fix by this weekend.

**Comment by ShreyasZare** [comment] 2021-04-02 15:23
@tkpaul92 how is it going? Did you see the same errors (System.IndexOutOfRangeException) in the logs?

**Comment by tkpaul92** [comment] 2021-04-02 19:00
> @tkpaul92 how is it going? Did you see the same errors (System.IndexOutOfRangeException) in the logs?

hello!

no, in fact I removed the service restart task on Monday and have not seen the problem come up again since then, thank you for your efforts.
What confuses me a bit is... why was this seemingly only affecting me?
I dont think my setup is in any way unique or special...

**Comment by ShreyasZare** [comment] 2021-04-03 06:13
> hello!
> 
> no, in fact I removed the service restart task on Monday and have not seen the problem come up again since then, thank you for your efforts.

Great to know that! 

> What confuses me a bit is... why was this seemingly only affecting me?
> I dont think my setup is in any way unique or special...

Its mostly some domain name that was causing the issue when it was being resolved. The thing is that most of the authoritative servers (the ones hosting domain names) work well but there are a few which are misconfigured and return strange responses which triggers errors if the condition was not handled correctly. So, I have to make sure that the DNS server correctly handle all the bad responses.

So, there are a few more bugs discovered which are being fixed and require some testing. There should be new update available by next weekend.

**Comment by ShreyasZare** [comment] 2021-04-10 12:50
Just released v6.1 that fixes the issue. Since you have a beta release installed, you wont see update notification on the web console. So, do install the update manually. 

Open the issue again if you find its not fixed.

**Closed by ShreyasZare** 2021-04-10 12:50 UTC
