### ISSUE TITLE
Use of BufferedStream is pointless

### ISSUE THREAD

**Issue by Matthew-Bonner** [TechnitiumSoftware/DnsServer#18] opened 2018-12-08 21:03 UTC
Stop using buffered streams, you are just making the library more complex than it needs to be, ie:

using (BufferedStream bS = new BufferedStream(new FileStream(hourlyStatsFile, FileMode.Create, FileAccess.Write)))

Read up about this at:
https://blogs.msdn.microsoft.com/brada/2004/04/15/filestream-and-bufferedstream/

**Comment by ShreyasZare** [comment] 2018-12-15 12:45
The issue is fixed with release of DNS Server v2.1. Please download and install the new release.

**Closed by ShreyasZare** 2018-12-15 12:45 UTC
