### ISSUE TITLE
Socket timeout too high for production environment

### ISSUE THREAD

**Issue by Matthew-Bonner** [TechnitiumSoftware/DnsServer#25] opened 2018-12-09 16:54 UTC
I propose changing the following:
const int TCP_SOCKET_SEND_TIMEOUT = 10000;
const int TCP_SOCKET_RECV_TIMEOUT = 60000;

to:
const int TCP_SOCKET_SEND_TIMEOUT = 2000;
const int TCP_SOCKET_RECV_TIMEOUT = 2000;

to prevent attacks that are aimed at exhausting resources on the dns server.

Bind itself actually uses 2 seconds as an appropriate timeout also, and Bind is considered the defacto standard in DNS server software.

**Comment by ShreyasZare** [comment] 2018-12-10 06:00
These defaults are set as per DNS over TCP (RFC 7766) to keep alive connections for reuse by clients. The options will be made configurable in later releases and the DoS security mitigations will be added later.

**Comment by ShreyasZare** [comment] 2018-12-15 12:48
The issue is fixed with release of DNS Server v2.1. Made the constants as configurable variables in the code with default set to 10 sec. API and GUI options for these parameters will come up in later updates.

**Closed by ShreyasZare** 2018-12-15 12:48 UTC
