### ISSUE TITLE
Save settings redirection

### ISSUE THREAD

**Issue by EHRETic** [TechnitiumSoftware/DnsServer#257] opened 2021-04-21 05:48 UTC
Hi there,

I have a little issue since a couple of versions already (can't say if it was the case when I started using the Technitium), which is: whenever I save settings in the options section, the server tries to redirect me to the URL https://server.fqdn:53443/
It is even weirder because I don't have the HTTPS option enabled in the console.

But I'm using NGINX to "protect" the server by accessing the web console on port 443 (NGINX is my standard method to protect web consoles)

If possible, Id' like to keep NGINX just as a matter of standardisation but that involves having the possibility to either not redirect the console or create an option to tell the server which "official" URL he is accessed from.
Every other section of the console is working great.

Any advice? Thanks in advance 😉

PS: I'm telling it almost every time now: SUPER GREAT software, I love it! 😃

**Comment by ShreyasZare** [comment] 2021-04-21 06:59
Thanks for the feedback and compliments!

I confirmed this issue which is in the javascript code. This feature was added to redirect the url when you save settings so that if you had changed the port in the settings, you would get automatically redirected to the new port. So, since you have nginx running the panel on different port, the script condition triggers due to mismatch with the port in the url and the port in the settings.

I will try to get this fixed with this scenario or if there is no proper solution then will remove this redirection code with some message box with detailed instructions.

Meanwhile, you can just check the Enable HTTPS checkbox, set web service HTTPS port to 443, uncheck the Enable HTTPS checkbox again, and save settings. This will make the nginx 443 port match with the port in the settings and prevent the JS from doing the redirection.

**Comment by ShreyasZare** [comment] 2021-04-24 10:28
This issue is fixed in the latest update v6.2.2. Do update and check if its working well.

**Closed by ShreyasZare** 2021-04-24 10:28 UTC

**Comment by EHRETic** [comment] 2021-04-24 11:50
Works great, thanks a lot (one more time)! 😉
