### ISSUE TITLE
Forward zones behaves erratically

### ISSUE THREAD

**Issue by agneevX** [TechnitiumSoftware/DnsServer#383] opened 2022-04-15 13:00 UTC
Hello,

I have forwarding enabled for `akamai.net`, however it seems that it takes two queries before the forwarded query is actually returned:

```sh
 ~> dig @localhost -p 5000 live09p.hotstar.com +short && sleep 30 && dig @localhost -p 5000 live09p.hots
tar.com +short
live09.akt.hotstar-cdn.net.akamaized.net.
a253.dscw43.akamai.net.
23.201.47.25
23.201.47.32
live09.akt.hotstar-cdn.net.akamaized.net.
a253.dscw43.akamai.net.
203.171.247.219
```

**Comment by ShreyasZare** [comment] 2022-04-15 13:09
Thanks for the feedback. Please share the forwarder zone config that you have so that I can test it from my end.

**Comment by agneevX** [comment] 2022-04-15 14:20
Thanks for getting back!

This is a fresh install and onboarding so I changed minimal configuration. 

In `Zones`, I added a new `Conditional Forwarder`, setting the zone name to `akamai.net`, and putting the relevant recursor's IP address and saved that.

In `Settings` -> `Proxy & Forwarders` -> `Forwarders`, I added my main recursor's IP details and saved that.

**Comment by ShreyasZare** [comment] 2022-04-15 15:11
Since the issue is not clearly understood, you will need to a test.First, go to the cache section on the dns web console and delete cached data for the affected domain.Now, use the DNS client on the web console and make the first query. Copy the output of the query. Make a second query and copy its output too.Post the output of both these queries here.

**Comment by agneevX** [comment] 2022-04-15 15:57
Initial query:

```json
{
  "Metadata": {
    "NameServer": "dns-server (127.0.0.1)",
    "Protocol": "Udp",
    "DatagramSize": "178 bytes",
    "RoundTripTime": "93.06 ms"
  },
  "EDNS": {
    "UdpPayloadSize": 1232,
    "ExtendedRCODE": "NoError",
    "Version": 0,
    "Flags": "None",
    "Options": [
      {
        "Code": "EDNS_CLIENT_SUBNET",
        "Length": "7 bytes",
        "Data": {
          "Data": "AAEYAHTBgg=="
        }
      }
    ]
  },
  "DnsClientExtendedErrors": [],
  "Identifier": 15974,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": false,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": true,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "NoError",
  "QDCOUNT": 1,
  "ANCOUNT": 4,
  "NSCOUNT": 0,
  "ARCOUNT": 1,
  "Question": [
    {
      "Name": "live09p.hotstar.com",
      "Type": "A",
      "Class": "IN"
    }
  ],
  "Answer": [
    {
      "Name": "live09p.hotstar.com",
      "Type": "CNAME",
      "Class": "IN",
      "TTL": "300 (5 mins)",
      "RDLENGTH": "42 bytes",
      "RDATA": {
        "Domain": "live09.akt.hotstar-cdn.net.akamaized.net"
      },
      "DnssecStatus": "Disabled"
    },
    {
      "Name": "live09.akt.hotstar-cdn.net.akamaized.net",
      "Type": "CNAME",
      "Class": "IN",
      "TTL": "21160 (5 hours 52 mins 40 sec)",
      "RDLENGTH": "21 bytes",
      "RDATA": {
        "Domain": "a253.dscw43.akamai.net"
      },
      "DnssecStatus": "Disabled"
    },
    {
      "Name": "a253.dscw43.akamai.net",
      "Type": "A",
      "Class": "IN",
      "TTL": "20 (20 sec)",
      "RDLENGTH": "4 bytes",
      "RDATA": {
        "IPAddress": "23.201.47.32"
      },
      "DnssecStatus": "Disabled"
    },
    {
      "Name": "a253.dscw43.akamai.net",
      "Type": "A",
      "Class": "IN",
      "TTL": "20 (20 sec)",
      "RDLENGTH": "4 bytes",
      "RDATA": {
        "IPAddress": "23.201.47.25"
      },
      "DnssecStatus": "Disabled"
    }
  ],
  "Authority": [],
  "Additional": [
    {
      "Name": "",
      "Type": "OPT",
      "Class": 1232,
      "TTL": "0 (0 sec)",
      "RDLENGTH": "11 bytes",
      "RDATA": {
        "Options": [
          {
            "Code": "EDNS_CLIENT_SUBNET",
            "Length": "7 bytes",
            "Data": {
              "Data": "AAEYAHTBgg=="
            }
          }
        ]
      },
      "DnssecStatus": "Indeterminate"
    }
  ]
}
```

Second query:

```json
{
  "Metadata": {
    "NameServer": "dns-server (127.0.0.1)",
    "Protocol": "Udp",
    "DatagramSize": "151 bytes",
    "RoundTripTime": "76.84 ms"
  },
  "EDNS": {
    "UdpPayloadSize": 1232,
    "ExtendedRCODE": "NoError",
    "Version": 0,
    "Flags": "None",
    "Options": []
  },
  "DnsClientExtendedErrors": [],
  "Identifier": 56901,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": false,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": true,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "NoError",
  "QDCOUNT": 1,
  "ANCOUNT": 3,
  "NSCOUNT": 0,
  "ARCOUNT": 1,
  "Question": [
    {
      "Name": "live09p.hotstar.com",
      "Type": "A",
      "Class": "IN"
    }
  ],
  "Answer": [
    {
      "Name": "live09p.hotstar.com",
      "Type": "CNAME",
      "Class": "IN",
      "TTL": "252 (4 mins 12 sec)",
      "RDLENGTH": "42 bytes",
      "RDATA": {
        "Domain": "live09.akt.hotstar-cdn.net.akamaized.net"
      },
      "DnssecStatus": "Disabled"
    },
    {
      "Name": "live09.akt.hotstar-cdn.net.akamaized.net",
      "Type": "CNAME",
      "Class": "IN",
      "TTL": "21112 (5 hours 51 mins 52 sec)",
      "RDLENGTH": "21 bytes",
      "RDATA": {
        "Domain": "a253.dscw43.akamai.net"
      },
      "DnssecStatus": "Disabled"
    },
    {
      "Name": "a253.dscw43.akamai.net",
      "Type": "A",
      "Class": "IN",
      "TTL": "20 (20 sec)",
      "RDLENGTH": "4 bytes",
      "RDATA": {
        "IPAddress": "202.78.239.171"
      },
      "DnssecStatus": "Disabled"
    }
  ],
  "Authority": [],
  "Additional": [
    {
      "Name": "",
      "Type": "OPT",
      "Class": 1232,
      "TTL": "0 (0 sec)",
      "RDLENGTH": "0 bytes",
      "RDATA": {
        "Options": []
      },
      "DnssecStatus": "Indeterminate"
    }
  ]
}
```

**Comment by ShreyasZare** [comment] 2022-04-17 10:14
Thanks for the details. This issue is due to how the forwarding is done. The DNS server fully trusts the configured forwarder in the settings so any response from it is cached including all CNAME records in the answer. While with conditional forwarders, only the response that is under the forwarder zone is used and cached.

In this case that you provided, you have created a conditional forwarder for "akamai.net" but the initial query is "live09p.hotstar.com" and thus does not fall under the conditional forwarder zone. So, the DNS server will use the configured forwarder in settings to resolve the domain name. The forwarder then returns an answer which is cached and served as an answer. 

Since "a253.dscw43.akamai.net" A records expire within 20 seconds, when the DNS server get the second query, it already has the CNAME records and only needs to resolve "a253.dscw43.akamai.net". So, now the domain to resolve matches the conditional forwarder and the query is now resolved via it. So, this conditional forwarder returns a different answer which is then cached and returned.

These CDN domain names resolve different IP addresses based on which IP address is querying for it. So both the forwarders in question have different IP addresses with them.

**Comment by agneevX** [comment] 2022-04-17 11:31
Thanks for the very detailed explanation. This proves to be a deal breaker, since I would want the recursor to actively chase and resolve CNAMEs in the chain, which I understand only works for the queried domain.

There are a couple of other issues that I've found in my testing that I thought I'd share:

1. Serve expired does not seem to work as intended. When a query in cache has 0 TTL, a subsequent query is served from upstream and not from cache (with a low TTL)
2. Refreshing the page logs me out.

**Comment by ShreyasZare** [comment] 2022-04-17 11:43
> Thanks for the very detailed explanation. This proves to be a deal breaker, since I would want the recursor to actively chase and resolve CNAMEs in the chain, which I understand only works for the queried domain.

If you don't configure a forwarder in settings then it would work that way as you expect. With the forwarder, the CNAME in response are trusted and also used as an optimization to prevent querying for the CNAME again to the same forwarder. But as you see in such cases, it becomes an issue.

So, I am now planning another analysis for this to see how it works when forwarder response with CNAME is truncated and queried separately. If it looks good then will add a small change to make it work as you had expected.

> There are a couple of other issues that I've found in my testing that I thought I'd share:
> 
>  1. Serve expired does not seem to work as intended. When a query in cache has 0 TTL, a subsequent query is served from upstream and not from cache (with a low TTL)

Records with 0 TTL that you see in cache are expired records which the DNS server would eventually remove from memory. But, if Serve Stale feature is enabled (which is by default enabled), then the expired records are not removed and kept for extended period specified by the serve stale TTL. This is done so that if the authoritative name server for that domain fails to respond for any reason then the expired records in the cache are used to answer queries.

>  2. Refreshing the page logs me out.

This is another issue which keeps coming up. You can read about it [here](https://www.reddit.com/r/technitium/comments/twby05/web_portal_keeps_asking_for_usernamepassword/). I am planning to give a rethink on it though since I initially didn't expect so many people being annoyed by it.

**Comment by agneevX** [comment] 2022-04-17 12:02
> So, I am now planning another analysis for this to see how it works when forwarder response with CNAME is truncated and queried separately. If it looks good then will add a small change to make it work as you had expected.

In Unbound, this is:

```yaml
forward-zone:
  name: "akamai.net"
  forward-addr: 172.19.0.20
```

> This is done so that if the authoritative name server for that domain fails to respond for any reason then the expired records in the cache are used to answer queries.

Ok. I assume the expired records are served after an upstream timeout? Is there any particular reason why it's not immediately served and an attempt to fetch the record is made in the background?

**Comment by ShreyasZare** [comment] 2022-04-17 12:11
> > This is done so that if the authoritative name server for that domain fails to respond for any reason then the expired records in the cache are used to answer queries.
> 
> Ok. I assume the expired records are served after an upstream timeout? Is there any particular reason why it's not immediately served and an attempt to fetch the record is made in the background?
 
This is done as per the [Serve Stale](https://www.rfc-editor.org/rfc/rfc8767.html) standard. If the DNS server does not receive a response for the query up to 1800ms then it will check if there is any expired data available in cache to use. The expired records are then set with 30 sec TTL value to keep the DNS server using it meanwhile the resolver retries in the background.

**Comment by ShreyasZare** [comment] 2022-05-08 12:34
Version 8.1 is now available that fixes this issue. Do test and confirm.

**Closed by ShreyasZare** 2022-05-08 12:34 UTC
