### ISSUE TITLE
Access problem to Dashboard

### ISSUE THREAD

**Issue by 84sigmapit** [TechnitiumSoftware/DnsServer#187] opened 2020-10-28 10:18 UTC
Hello after installation , i cant access to Dashboard panel. It is locked How i can active it ?

**Comment by ShreyasZare** [comment] 2020-10-28 10:20
Thanks for the post. How are you trying to access the panel? Is the DNS server installed on the same machine you are trying to access the web panel or is it on another machine on the network? What is the OS on the DNS server?

**Comment by 84sigmapit** [comment] 2020-10-28 10:36
I completed installation DNS server to my computer. Then when i start program from taskbar i saw Dashboard is not active. You may see in attached Screen Shot. There is no another machine 
![İssue](https://user-images.githubusercontent.com/73586728/97424937-7b1cce80-1922-11eb-9068-225d668f44f8.jpg)

**Comment by ShreyasZare** [comment] 2020-10-28 10:41
Thanks for the details. The Dashboard link is gets disabled when the DNS service is not running. Just check the 'Service' menu and see if the service is running, if not then click on the start menu item. Once the service starts then Dashboard link will get enabled.

**Comment by 84sigmapit** [comment] 2020-10-28 11:16
I apply exactly what you said.But After 'Service' and  'Start' menu i am getting this attached 
![Adsız](https://user-images.githubusercontent.com/73586728/97429238-31cf7d80-1928-11eb-94f9-2e9ee4504255.png)
 error.

**Comment by ShreyasZare** [comment] 2020-10-28 11:26
Thanks for the details. Its seems the service is not starting due to some issue. Check once in the Services console for Technitium DNS Server and check its status. To open it press Win+R to start Run and enter `services.msc` to open Services console.

You can check the DNS server logs and see if there are any errors logged in it. You can find the log files in `C:\Program Files (x86)\Technitium\DNS Server\config\logs` folder. If you find any errors then post them here.

You can try to reboot Windows once and see if the service is starting. If the service is still not starting then you need to check Windows event logs using the Event Viewer. Find any error that you see in the Event Viewer for the DNS server and post them here.

**Comment by 84sigmapit** [comment] 2020-10-28 12:30
[2020-10-28.log](https://github.com/TechnitiumSoftware/DnsServer/files/5451817/2020-10-28.log)
I took logs from (x86)\Technitium\DNS Server\config\logs. Could you check for me

**Comment by ShreyasZare** [comment] 2020-10-28 12:58
Thanks for the log file. The issue is that your computer's name contains non ASCII character. The DNS server uses the computer's name as its initial domain name and since the name is not a valid domain name, there is an error causing the DNS server to crash.

I will update the code to fix this issue in next release. But, for now, you can run the DNS server with this workaround:

1. Change your computer's name to contain only ASCII characters.
2. Restart the computer so that the system name is updated.
3. Once the computer starts, the DNS server will start too without any issues.

Let me know if there was any issue with this workaround.

**Comment by niekvb** [comment] 2020-10-31 23:41
Same (kind of) problem here:
```plainText
TechnitiumLibrary.Net.Dns.DnsClientException: Invalid domain name [desktop-pc-]: label cannot end with hyphen.
```

PC's name is set to: `DESKTOP-PC-2`

**Comment by ShreyasZare** [comment] 2020-11-02 07:50
> 
> 
> Same (kind of) problem here:
> 
> ```
> TechnitiumLibrary.Net.Dns.DnsClientException: Invalid domain name [desktop-pc-]: label cannot end with hyphen.
> ```
> 
> PC's name is set to: `DESKTOP-PC-2`

Thanks for the feedback. This will get fixed in the next release.

**Comment by EHRETic** [comment] 2020-11-08 16:39
> > Same (kind of) problem here:
> > ```
> > TechnitiumLibrary.Net.Dns.DnsClientException: Invalid domain name [desktop-pc-]: label cannot end with hyphen.
> > ```
> > 
> > 
> > PC's name is set to: `DESKTOP-PC-2`
> 
> Thanks for the feedback. This will get fixed in the next release.

Maaaaann, the day I discover Technitium and try it out, I discover as well that it doesn't support "-" in dns name... and all my machines have one ! ^^

Is it affecting also CentOS ? I've tried both local fqdn and IP, same result, seems not to respond (and firewall is open:

`public (active)
  target: default
  icmp-block-inversion: no
  interfaces: ens192
  sources: 
  services: cockpit dhcpv6-client dns ssh
  ports: 5480/tcp
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: `

Any fix to try out?

**Comment by ShreyasZare** [comment] 2020-11-08 16:44
> 
> 
> > > Same (kind of) problem here:
> > > ```
> > > TechnitiumLibrary.Net.Dns.DnsClientException: Invalid domain name [desktop-pc-]: label cannot end with hyphen.
> > > ```
> > > 
> > > 
> > > PC's name is set to: `DESKTOP-PC-2`
> > 
> > 
> > Thanks for the feedback. This will get fixed in the next release.
> 
> Maaaaann, the day I discover Technitium and try it out, I discover as well that it doesn't support "-" in dns name... and all my machines have one ! ^^
> 
> Is it affecting also CentOS ? I've tried both local fqdn and IP, same result, seems not to respond (and firewall is open:
> 
> `public (active) target: default icmp-block-inversion: no interfaces: ens192 sources: services: cockpit dhcpv6-client dns ssh ports: 5480/tcp protocols: masquerade: no forward-ports: source-ports: icmp-blocks: rich rules: `
> 
> Any fix to try out?

Its not an issue with "-" in the name, its when the machine name is read and due to the character limit on the name, the "-" comes in the end is when its not acceptable since a domain name cannot end with "-".

The next update will have this fixed so it wont be issue with machine name.

**Comment by EHRETic** [comment] 2020-11-08 19:36
> Its not an issue with "-" in the name, its when the machine name is read and due to the character limit on the name, the "-" comes in the end is when its not acceptable since a domain name cannot end with "-".
> 
> The next update will have this fixed so it wont be issue with machine name.

 Mines are srv-xxx-yy.domain.local, is ti also "supposed" to be affected? Just to be sure it's not something else... 😉

**Comment by ShreyasZare** [comment] 2020-11-09 06:12
> Mines are srv-xxx-yy.domain.local, is it also "supposed" to be affected? Just to be sure it's not something else... 😉

I don't know, you tell me if its causing issue. The issue is that `Environment.MachineName` is returning truncated name and in case there is a "-" at the end then it will cause an issue. Also, if there are non ASCII characters in the name then that too will cause issue since domain names can contain only ASCII characters.

Next update will have a check for this to handle it gracefully.

**Comment by ShreyasZare** [comment] 2020-11-10 12:17
> BTW, if I could get the "how to" SSL the admin console, it would be perfect (it doesn't seems to be in the doc anymore)

Unfortunately the built in web server that is being used does not support SSL. There is a plan to replace it in later updates. For now, I would recommend that you do reverse proxy with nginx or any other web server.

**Comment by EHRETic** [comment] 2020-11-10 17:14
> Unfortunately the built in web server that is being used does not support SSL. There is a plan to replace it in later updates. For now, I would recommend that you do reverse proxy with nginx or any other web server.

I know how to do that, no worries :-)

**Comment by EHRETic** [comment] 2020-11-12 14:55
> Unfortunately the built in web server that is being used does not support SSL. There is a plan to replace it in later updates. For now, I would recommend that you do reverse proxy with nginx or any other web server.

So I did install nginx to use SSL for the Dasboard, it's nice to have a secure way to access it.

**Note for the people** (like me) that doesn't know Linux "so good" : if you have SELinux active, **it will not let nginx access another port** and you will end up with a 502 gateway error.
For me it was pretty easy to solve because SELinux in Cockpit will give you all the required commands but I don't know how this would work if you don't use Cockpit.

My 5 cents, just in case somebody is struggling and getting 502... 😉

**Comment by ShreyasZare** [comment] 2020-11-14 13:16
Version 5.5 released which fixes this issue.

**Closed by ShreyasZare** 2020-11-14 13:16 UTC
