### ISSUE TITLE
Log ####___TRUNCATED___#### when download from webui

### ISSUE THREAD

**Issue by Globulopolis** [TechnitiumSoftware/DnsServer#114] opened 2020-01-13 14:46 UTC
Log downloaded as truncated and even in `preLogViewerBody`. I can understand why you limit logsize to 2Mb for `in browser view`, but it should download whole file from server.
Browser returning previously cached result from request in downloadLog() function.

Firefox 72.0.1 x64

**Comment by ShreyasZare** [comment] 2020-01-14 06:35
Thanks for the feedback. This can happen when you download the current date log file and is not a bug. The log file is already being written while you are downloading it and if there are more bytes written to the log while your download finishes, the truncated indicator is appended. 

This just means that the log file got updated while you were downloading it.

**Comment by Globulopolis** [comment] 2020-01-14 07:38
No. Older logs download truncated if they more than 2Mb. To avoid this for requests you need to add curent timestamp in URL.

**Comment by ShreyasZare** [comment] 2020-01-14 07:50
Thanks for the analysis. Seems to be browser cache issue which may occur in such scenario. Will add timestamp to the download url.

**Comment by ShreyasZare** [comment] 2020-07-05 11:18
Issue fixed in new release.

**Closed by ShreyasZare** 2020-07-05 11:18 UTC
