### ISSUE TITLE
Option to delete cached zones do not work

### ISSUE THREAD

**Issue by crowley666x** [TechnitiumSoftware/DnsServer#51] opened 2019-05-29 19:36 UTC
When I try to delete a cached zone, the zone do not delete. The returned message it's OK, but nothing happen.
I´m using Technitium DNS Server Version 3.3

Thanks

**Comment by ShreyasZare** [comment] 2019-05-30 09:09
Thanks for the feedback.

Cache delete option will remove the currently displayed entry. The option works well, I am using it frequently for testing purposes.

In your case, it may be that the cache is getting populated again for the deleted domain name. It may be that the server received query for the domain and thus it got cached again or if the domain is satisfying the auto prefetch eligibility criteria, the server will automatically refresh cache for that domain name.

**Comment by ShreyasZare** [comment] 2019-06-29 08:48
closing issue since issue is not reproducible and works as intended.

**Closed by ShreyasZare** 2019-06-29 08:48 UTC
