### ISSUE TITLE
TechnitiumDNS Server sometimes missing some Root-Domains

### ISSUE THREAD

**Issue by Sysadminfromhell** [TechnitiumSoftware/DnsServer#418] opened 2022-06-24 16:20 UTC
Hey there,

today i experienced the following problem with the device of my wife:
She used Amazon Games to download games from Amazon Prime Gaming, the Installer couldnt find the cloudflare.net domain.
I searched the Cache and couldnt find the requested hostname. Is theyre any way to "update" or "refresh" the root-domain servers like in BIND or UNBOUND?

Kind regards,

**Comment by ShreyasZare** [comment] 2022-06-25 05:46
Thanks for the feedback. I tested for the domain from multiple setups and its resolving fine without any issues. It could be a temporary issue at your end and the domain should resolve when the DNS server retries for it. Check your DNS logs for errors which will give you exact reason why the resolution failed.

There is no need to update or refresh root name servers as they do not change.

**Comment by Sysadminfromhell** [comment] 2022-06-25 20:03
Sometimes I see this:

TechnitiumLibrary.Net.Dns.DnsClientNoResponseException: DnsClient recursive resolution failed: no response from name servers [in-addr.ch, in-addr.ps].
   at TechnitiumLibrary.Net.Dns.DnsClient.RecursiveResolveAsync(DnsQuestionRecord question, IDnsCache cache, NetProxy proxy, Boolean preferIPv6, UInt16 udpPayloadSize, Boolean randomizeName, Boolean qnameMinimization, Boolean asyncNsRevalidation, Boolean dnssecValidation, Int32 retries, Int32 timeout, Int32 maxStackCount, Boolean cleanupResponse, CancellationToken cancellationToken) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 1537
   at DnsServerCore.Dns.DnsServer.RecursiveResolveAsync(DnsQuestionRecord question, IReadOnlyList`1 conditionalForwarders, Boolean dnssecValidation, Boolean cachePrefetchOperation, Boolean cacheRefreshOperation, TaskCompletionSource`1 taskCompletionSource) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 2261

How can I fix this?

**Comment by ShreyasZare** [comment] 2022-06-26 11:17
These are quite normal operational issues for a recursive resolver. There can be packet drops caused by network congestion causing requests to timeout. Usually, DNS cache with serve stale feature enabled will minimize such issues by using old data from cache. The issue usually resolves automatically when the DNS server retries again later.

**Comment by ShreyasZare** [comment] 2022-07-03 11:21
New update v8.1.4 is now available which fixes an issue that is probably related to the error you posted. Do update and let me know if you see those errors again. Closing this issue for now.

**Closed by ShreyasZare** 2022-07-03 11:21 UTC
